FROM gradle:jdk17-alpine
ARG PRODUCTION
ARG JDBC_DATABASE_PASSWORD
ARG JDBC_DATABASE_URL
ARG JDBC_DATABASE_USERNAME

ARG REDIS_URL
ARG RABBITMQ_URL

ENV PRODUCTION ${PRODUCTION}
ENV JDBC_DATABASE_PASSWORD ${JDBC_DATABASE_PASSWORD}
ENV JDBC_DATABASE_URL ${JDBC_DATABASE_URL}
ENV JDBC_DATABASE_USERNAME ${JDBC_DATABASE_USERNAME}

ENV REDIS_URL ${REDIS_URL}
ENV RABBITMQ_URL ${RABBITMQ_URL}

WORKDIR /app
COPY ./build/libs/scheduling_service-0.0.1-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java","-jar","scheduling_service-0.0.1-SNAPSHOT.jar"]